name: React App CI/CD Pipeline

# Workflow ko trigger karne ka condition
on:
  push:
    branches:
      - main  # Jab main branch pe push hoga, workflow chalega
  pull_request:
    branches:
      - main  # Jab main branch pe pull request hoga, workflow chalega

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Ye GitHub ka Ubuntu server pe run hoga

    steps:
      # Step 1: Code ko checkout karen
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Node.js setup karen
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.5.1'  # React app ke liye Node.js version

      # Step 3: Dependencies install karen
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional)
      - name: Run tests
        run: npm test -- --watchAll=false --coverage

      # Step 5: React app build karen
      - name: Build the app
        run: npm run build

      # Step 6: Deploy to Netlify (example)
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # GitHub Secrets mein store kiya hua token
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}  # GitHub Secrets mein store kiya hua Site ID
        run: |
          curl -sL https://github.com/netlify/cli/releases/download/v3.4.0/netlify-cli-linux-x64.tar.gz | tar xz
          sudo mv netlify /usr/local/bin/netlify
          netlify deploy --dir=build --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
